dist: trusty

matrix:
  include:
    - language: python
      python: "3.6"
      os: linux
      install:
        - pip3 install jinja2
    - language: generic
      os: osx
      install:
        - pip2 install jinja2
        - pip3 install jinja2


script:
    - ( cd tests; ./run_tests.sh )
